[project]
name = "trpg-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "atomic-agents>=2.0.4",
    "openai>=1.100.2",
    "openai-agents>=0.2.8",
    "ruamel-yaml>=0.18.15",
    "smolagents[toolkit]>=1.21.2",
]
